# Setup
title: Cory Gordinier
tagline: Professional software engineer, amateur mechanic and race car driver, tall person.
url: https://corygordinier.com
baseurl: "" # FIXME: you will probably replace this with ""
permalink: /posts/:year/:title/

kramdown:
  footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# FIXME: decide if you want google analytics
# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

social:
    - title: facebook
      address: https://www.facebook.com/cory.gordinier
      class: fab fa-facebook
    - title: instagram
      address: https://www.instagram.com/cgordini/
      class: fab fa-instagram
    - title: twitter
      address: https://www.twitter.com/cgordini/
      class: fab fa-twitter
    - title: twitch
      address: https://www.twitch.tv/cgordini
      class: fab fa-twitch
    - title: youtube
      address: https://www.youtube.com/channel/UC8yxeZmwfM0Eao_TOIPJn0Q
      class: fab fa-youtube
    - title: github
      address: https://github.com/cgordini/
      class: fab fa-github

nav:
  # each has a name (the path) and optionally, a label (to show in the nav bar)
  # FIXME: add/customize these as desired
  - name: about
  - name: contact
    # label: contact me
  - name: news

author:
  name: Cory Gordinier

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_posts"
    values:
      layout: "post" # overrides previous default layout
